# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJUqTuykAhZrHrFhNB2TBBhQm9P7qTEl
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# Load sentiment analysis model
setiment = pipeline("sentiment-analysis")

# Sample product review (you can change only this text later)
reviews = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming.
"""

import pandas as pd
from transformers import pipeline

# Define review text (IMPORTANT)
reviews = "The product is amazing. I love the battery life. The screen is dull. Customer service was terrible."

# Load sentiment model
sentiment = pipeline("sentiment-analysis")

# Split review into sentences
sentences = reviews.split(".")

pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue

    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)

    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})

df