# -*- coding: utf-8 -*-
"""SENTENCE SILMARTY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcUkih54I_MdygSxHNmoBKlcbt6luVS2
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

model =SentenceTransformer('all-MiniLM-L6-v2')
text1 =input("enter the text 1: ")
text2 =input("enter the text 2: ")

embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

Similarity = util.cos_sim(embedding1, embedding2)
print("/nSimilarity Score:", round(float(Similarity), 2))

if Similarity>0.75:
  print("Similarity Level:HIGH")
elif Similarity>0.4:
    print("Similsrity level:MEDIUM")
else:
    print("Similarity Level:LOW")